# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9569533475638da2b742c4eb3ccfef3729a2707d4284b0e8422cb5d0b1042365ee10ad1478058b3dcda860e11b1d96db9f21a68cfb0fa283b9208442fffccc9c

test:
  secret_key_base: 27bc85448b14ac3bea2edceb68215cce13fd8429ef657f963d634a5411dbd6b6a5bd5f692cd4ff36e19532de009108106838c270b90654fa072b224704cde909

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
